package com.mathspeed.adapter.network.protocol;

public enum MessageType {
    LOGIN_REQUEST, LOGIN_SUCCESS, LOGIN_FAILED, REGISTER_SUCCESS, LOGOUT,
    PING, PONG, TIME_PING, PLAYER_LIST_UPDATE,
    JOIN_QUEUE, LEAVE_QUEUE, QUEUE_JOINED, QUEUE_LEFT,
    CHALLENGE_REQUEST, CHALLENGE_SENT, CHALLENGE_RECEIVED, CHALLENGE_ACCEPTED, CHALLENGE_DECLINED, CHALLENGE_EXPIRED, CHALLENGE_FAILED, INFO,
    GAME_START, NEW_QUESTION, SUBMIT_ANSWER, ANSWER_RESULT, GAME_END, REMATCH_REQUEST, REMATCH_RESPONSE,
    MATCH_START_INFO, NEW_ROUND, ROUND_RESULT, GAME_OVER,
    FORFEIT_REQUEST, FORFEIT_ACK,
    SERVER_BUSY, ERROR, DISCONNECT
}
